### ISSUE TITLE
Error when launching the .py

### ISSUE THREAD

**Issue by Lunyyx** [xXM0NST3RXx/iSQL#1]
Traceback (most recent call last):
  File "iSQL.py", line 82, in <module>
    print("\nCoded BY: "+colored("M0NST\u018eR","yellow")+" & "+colored("Sniper-UMS\n","cyan"))
UnicodeEncodeError: 'ascii' codec can't encode character '\u018e' in position 21: ordinal not in range(128)

If you want more additionnal info, just tell me

**Comment by pillowz6666** [comment]
I'm a noob to scripting but try run these commands
sudo pip3 install yellow
sudo pip3 install cyan

**Comment by GeniusNerd695** [comment]
pip install all libraries used in the code ( probably termcolor)

**Comment by EVOLCORE** [comment]
Traceback (most recent call last):
  File "iSQL.py", line 34, in <module>
    import docs.proxies
  File "/root/iSQL/iSQL/docs/proxies.py", line 1, in <module>
    import requests
ImportError: No module named 'requests'
